### ISSUE TITLE
v0.0.4 error on startup: `no such directory: /project/.storybook/page-data/sq/d`

### ISSUE THREAD

**Issue by sklawren** [prismicio-community/storybook-addon-gatsby#6]
### Versions

- package_name: storybook-addon-gatsby
- node: 16.13.2
- gatsby: 3.14.3

### Reproduction

I updated from 0.0.3 to 0.0.4 and Storybook build broke locally and on Chromatic with the following error:
```
info => Loading presets
/project/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:118
throw new Error((0, _tsDedent.default)((0, _chalk.default)`
^
Error: Failed to load static files, no such directory: /project/.storybook/page-data/sq/d
Make sure this directory exists, or omit the -s (--static-dir) option.
at parseStaticDir
```

I rolled back to 0.0.3 and it works again.

**Comment by sklawren** [comment]
I manually copy+pasted the addon code into my storybook main.js and preview.js and it works.

The only difference between 0.0.3 and 0.0.4 is some dependencies in package-lock.json, though it's not clear which one(s) because github can't diff a large file, but it's definitely breaking because of this.

**Comment by angeloashmore** [comment]
Hey @sklawren, the change between 0.0.3 and 0.0.4 is supporting Gatsby's static queries (i.e. `useStaticQuery()` and `<StaticQuery>`).

You can see the changes in this commit: https://github.com/prismicio-community/storybook-addon-gatsby/commit/4014db558c10a5fcaf93fd5599c167f4061dcc80

Perhaps the addon could check the filesystem for that directory and conditionally apply static query support.

This is a community-run package so please feel free to contribute a PR. :)

**Comment by angeloashmore** [comment]
@sklawren @feedm3 If you're able to, could you test out `v0.0.5` and let me know if it fixes the error?

It removes the `page-data/sq/d` static directory from the Storybook config. It shouldn't be necessary with the way Gatsby resolves static queries now. This path was apparently incorrect anyway (as it is relative to the `.storybook` directory, not the root of the project).

Thanks!

**Comment by feedm3** [comment]
The new version is working again, thank you very much for fixing it 🙂
